// <auto-generated />
using Mango.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CatgoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CatgoryName = "Bajaj",
                            Description = "This is an Fan manufactured by Bajaj",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Bajaj Fans",
                            Price = 2000.0
                        },
                        new
                        {
                            ProductId = 2,
                            CatgoryName = "Bajaj",
                            Description = "This is an Cooler manufactured by Bajaj",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "Bajaj Cooler",
                            Price = 8000.0
                        },
                        new
                        {
                            ProductId = 3,
                            CatgoryName = "Whirlpool",
                            Description = "This is an Washing Machine manufactured by Whirlpool",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "Whirlpool washing Machine",
                            Price = 17000.0
                        },
                        new
                        {
                            ProductId = 4,
                            CatgoryName = "Hitachi",
                            Description = "This is an AC manufactured by Hitachi",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Hitachi AC",
                            Price = 25000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
